spring:
  cloud:
    gateway:
      routes:
        - id: member_route
          uri: lb://zcourse-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: zcourse_route
          uri: lb://zcourse-course
          predicates:
            - Path=/api/course/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: auth_route
          uri: lb://zcourse-auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}